platform :ios, '12.0'
workspace 'Watcher'
use_frameworks!

target 'Watcher' do
  project 'Watcher'
  
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod 'SwiftLint'
  pod 'RealmSwift'
  
  target 'Transport' do
    project 'Transport/Transport'
    inherit! :search_paths
    
    target 'TransportTests' do
      inherit! :search_paths
    end
  end
end
